config/routes.rb
Contas::Application.routes.draw do

  root to: "home#home"

  get "home/help"
  get "home/novoMes"
  resources :transfers
  resources :despesas
  resources :users

end

app/models/despesa.rb
class Despesa < ActiveRecord::Base
	belongs_to :user, :foreign_key => :usr_pag
	validates_presence_of :nome, :mes_ref, :ano_ref,  message: "nao pode estar em branco."
end

app/models/transfer.rb
class Transfer < ActiveRecord::Base
	validates_presence_of :usr_pagante, :usr_destino
	validates :valor, :numericality => {:greater_than => 0}
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :despesas
	validates_presence_of :nome, :banco, :agencia, :conta
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/despesas_controller.rb
class DespesasController < ApplicationController
  before_action :set_despesa, only: [:show, :edit, :update, :destroy]

  # GET /despesas
  # GET /despesas.json
  def index
    @despesas = Despesa.includes(:user).order(:ano_ref, :mes_ref)
  end

  # GET /despesas/1
  # GET /despesas/1.json
  def show
  end

  # GET /despesas/new
  def new
    @despesa = Despesa.new
  end

  # GET /despesas/1/edit
  def edit
  end

  # POST /despesas
  # POST /despesas.json
  def create
    @despesa = Despesa.new(despesa_params)

    respond_to do |format|
      if @despesa.save
        format.html { redirect_to despesas_path, notice: 'Despesa criada com sucesso  .' }
        format.json { render action: 'show', status: :created, location: @despesa }
      else
        format.html { render action: 'new' }
        format.json { render json: @despesa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /despesas/1
  # PATCH/PUT /despesas/1.json
  def update
    respond_to do |format|
      if @despesa.update(despesa_params)
        format.html { redirect_to despesas_path, notice: 'A Despesa "'+@despesa.nome+'" ('+sprintf('%02d',@despesa.mes_ref)+'/'+@despesa.ano_ref.to_s+') foi alterada com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @despesa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /despesas/1
  # DELETE /despesas/1.json
  def destroy
    @despesa.destroy
    respond_to do |format|
      format.html { redirect_to despesas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_despesa
      @despesa = Despesa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def despesa_params
      params.require(:despesa).permit(:nome, :valor, :recorrente, :mes_ref, :ano_ref, :usr_pag)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  	@users = User.all
  	@despesas = Despesa.includes(:user)
    @anos = Despesa.select(:ano_ref).distinct
    @meses = Despesa.select(:mes_ref, :ano_ref).distinct
  end

  def help
  end

  def novoMes
  	@despesas = Despesa.where(:ano_ref => Despesa.maximum(:ano_ref), :mes_ref => Despesa.maximum(:mes_ref), :recorrente => 1)

    @despesas.each do |d|
      @despesa = Despesa.new(nome: d.nome, ano_ref: d.ano_ref, mes_ref: (d.mes_ref+1), valor: d.valor, recorrente: d.recorrente)
      @despesa.save
    end
      
      redirect_to root_path

  end

end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :set_transfer, only: [:show, :edit, :update, :destroy]

  # GET /transfers
  # GET /transfers.json
  def index
    @transfers = Transfer.all
  end

  # GET /transfers/1
  # GET /transfers/1.json
  def show
  end

  # GET /transfers/new
  def new
    @transfer = Transfer.new
  end

  # GET /transfers/1/edit
  def edit
  end

  # POST /transfers
  # POST /transfers.json
  def create
    @transfer = Transfer.new(transfer_params)

    respond_to do |format|
      if @transfer.save
        format.html { redirect_to @transfer, notice: 'Transfer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @transfer }
      else
        format.html { render action: 'new' }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transfers/1
  # PATCH/PUT /transfers/1.json
  def update
    respond_to do |format|
      if @transfer.update(transfer_params)
        format.html { redirect_to @transfer, notice: 'Transfer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transfers/1
  # DELETE /transfers/1.json
  def destroy
    @transfer.destroy
    respond_to do |format|
      format.html { redirect_to transfers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transfer
      @transfer = Transfer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transfer_params
      params.require(:transfer).permit(:usr_pagante, :usr_destino, :valor)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:nome, :banco, :agencia, :conta)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/despesas_helper.rb
module DespesasHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/despesas/_form.html.erb
<%= form_for(@despesa) do |f| %>
  <% if @despesa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@despesa.errors.count, "error") %> prohibited this despesa from being saved:</h2>

      <ul>
      <% @despesa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :valor %><br>
    <%= f.text_field :valor %>
  </div>
  <div class="field">
    <%= f.label :recorrente %><br>
    <%= f.check_box :recorrente %>
  </div>
  <div class="field">
    <%= f.label :mes_ref %><br>
    <%= f.number_field :mes_ref %>
  </div>
  <div class="field">
    <%= f.label :ano_ref %><br>
    <%= f.number_field :ano_ref %>
  </div>
  <div class="field">
    <%= f.label :usr_pag %><br>
    <%= f.number_field :usr_pag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/despesas/edit.html.erb
<h1>Editing despesa</h1>

<%= render 'form' %>

<%= link_to 'Show', @despesa %> |
<%= link_to 'Back', despesas_path %>

app/views/despesas/index.html.erb
<h1>Despesas</h1>

<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Valor</th>
      <th>Recorrente?</th>
      <th>Mês Referência</th>
      <th>Ano Referência</th>
      <th>Pagante</th>
    </tr>
  </thead>

  <tbody>
    <% @despesas.each do |d| %>
      <tr>
        <td><%= d.nome %></td>
        <td>R$: <%= d.valor %></td>
        <td><%= d.recorrente? ? 'Sim' : 'Não' %></td>
        <td><%= Date::MONTHNAMES[d.mes_ref] %></td>
        <td><%= d.ano_ref %></td>
        <td><%= d.usr_pag.nil? ?  'Sem Usuário Pagante' : d.user.nome %></td>
        <td><%= link_to 'Editar', edit_despesa_path(d) %></td>
        <td><%= link_to 'Deletar', d, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Despesa', new_despesa_path %><br>
<%= link_to 'Home', root_path %>

app/views/despesas/new.html.erb
<h1>New despesa</h1>

<%= render 'form' %>

<%= link_to 'Back', despesas_path %>

app/views/despesas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @despesa.nome %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @despesa.valor %>
</p>

<p>
  <strong>Recorrente:</strong>
  <%= @despesa.recorrente %>
</p>

<p>
  <strong>Mes ref:</strong>
  <%= @despesa.mes_ref %>
</p>

<p>
  <strong>Ano ref:</strong>
  <%= @despesa.ano_ref %>
</p>

<p>
  <strong>Usr pag:</strong>
  <%= @despesa.usr_pag %>
</p>

<%= link_to 'Edit', edit_despesa_path(@despesa) %> |
<%= link_to 'Back', despesas_path %>

app/views/home/_form.html.erb
<%= simple_form_for @despesa do |f| %>
  <% if @despesa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@despesa.errors.count, "error") %> prohibited this despesa from being saved:</h2>

      <ul>
      <% @despesa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :nome, :input_html => {:size => 30} %>
  </div>
  <div class="field">
    <%= f.input :valor %>
  </div>
  <div class="field">
    <%= f.input :recorrente, as: :boolean %>
  </div>
  <div class="field">
    <%= f.input :mes_ref %>
  </div>
  <div class="field">
    <%= f.input :ano_ref %>
  </div>
  <div class="field">
    <%= f.input :usr_pag, collection: User.all, label_method: :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/home/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/home/home.html.erb
<h1>Página Principal</h1>

<nav>
	<ul>
		<li><%= link_to 'Usuários', users_path %></li>
		<li><%= link_to 'Despesas', despesas_path %></li>
		<li><%= link_to 'Transferências', transfers_path %></li>
		<li><%= link_to 'Gerar Novo Mês', :controller => 'home', :action => 'novoMes' %></li>
	</ul>
</nav>

<% @anos.each do |ano|%>
	<div class='tables'>
		<table class='home-table'>
			
			<thead>
				<th class='year-head' colspan='4'>
					<%= ano.ano_ref.to_s %>
				</th>
				<% for i in 1..12 %>
					<tr>
						<th class='month-head' colspan='4'><%= Date::MONTHNAMES[i] %></th>
					</tr>
					<tr>
						<th>Despesa</th>
						<th>Valor</th>
						<th>Pagante</th>
						<th>Editar</th>
					</tr>
			</thead>

			<tbody>
					<% @despesas.where(:ano_ref => ano.ano_ref, :mes_ref => i).each do |d| %>
						<tr>
							<td><%= d.nome %></td>
							<td><%= 'R$ '+d.valor.to_s %></td>
							<td><%= d.usr_pag.nil? ?  'Sem Usuário Pagante' : d.user.nome %></td>
							<td><%= link_to 'Editar', edit_despesa_path(d) %></td>
						</tr>
					<% end %>
				<% end %>
			</tbody>

		</table>
	</div>
<% end %>

app/views/home/novoMes.html.erb
<h1> Despesas que já possuem Pagante </h1>

<% @despesas.each do |d| %>
	<div>
	<%= "Despesa: "+d.nome %><br>
	<%= "Valor: R$ "+d.valor.to_s %><br>
	<%= "Mês: "+d.mes_ref.to_s %><br>
	<%= "Ano: "+d.ano_ref.to_s %><br>
	<%= "Recorrente: "+(d.recorrente ? 'Sim': 'Não') %><br>
	<%= d.usr_pag.nil? ? 'Sem usuário Pagante' : "Usuário: "+d.user.nome %>
	</div>
	<br>
<% end %>

<%= link_to 'Home', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contas</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/transfers/_form.html.erb
<%= simple_form_for(@transfer) do |f| %>
  <% if @transfer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transfer.errors.count, "error") %> prohibited this transfer from being saved:</h2>

      <ul>
      <% @transfer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :usr_pagante, collection: User.all, label_method: :nome, label: 'Pagante' %>
  </div>
  <div class="field">
    <%= f.input :usr_destino, collection: User.all, label_method: :nome, label: 'Destino' %>
  </div>
  <div class="field">
    <%= f.input :valor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transfers/edit.html.erb
<h1>Editing transfer</h1>

<%= render 'form' %>

<%= link_to 'Show', @transfer %> |
<%= link_to 'Back', transfers_path %>

app/views/transfers/index.html.erb
<h1>Transferências</h1>

<table>
  <thead>
    <tr>
      <th>Usr pagante</th>
      <th>Usr destino</th>
      <th>Valor</th>
    </tr>
  </thead>

  <tbody>
    <% @transfers.each do |transfer| %>
      <tr>
        <td><%= transfer.usr_pagante %></td>
        <td><%= transfer.usr_destino %></td>
        <td><%= transfer.valor %></td>
        <td><%= link_to 'Show', transfer %></td>
        <td><%= link_to 'Edit', edit_transfer_path(transfer) %></td>
        <td><%= link_to 'Destroy', transfer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transfer', new_transfer_path %><br>
<%= link_to 'Home', root_path %>

app/views/transfers/new.html.erb
<h1>New transfer</h1>

<%= render 'form' %>

<%= link_to 'Back', transfers_path %>

app/views/transfers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usr pagante:</strong>
  <%= @transfer.usr_pagante %>
</p>

<p>
  <strong>Usr destino:</strong>
  <%= @transfer.usr_destino %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @transfer.valor %>
</p>

<%= link_to 'Edit', edit_transfer_path(@transfer) %> |
<%= link_to 'Back', transfers_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :banco %><br>
    <%= f.text_field :banco %>
  </div>
  <div class="field">
    <%= f.label :agencia %><br>
    <%= f.text_field :agencia %>
  </div>
  <div class="field">
    <%= f.label :conta %><br>
    <%= f.text_field :conta %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Usuários</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Banco</th>
      <th>Agencia</th>
      <th>Conta</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nome %></td>
        <td><%= user.banco %></td>
        <td><%= user.agencia %></td>
        <td><%= user.conta %></td>
        <td><%= link_to 'Editar', edit_user_path(user) %></td>
        <td><%= link_to 'Deletar', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Usuário', new_user_path %><br>
<%= link_to 'Home', root_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @user.nome %>
</p>

<p>
  <strong>Banco:</strong>
  <%= @user.banco %>
</p>

<p>
  <strong>Agencia:</strong>
  <%= @user.agencia %>
</p>

<p>
  <strong>Conta:</strong>
  <%= @user.conta %>
</p>

<%= link_to 'Editar', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>